services:
    php:
        ports:
            - "8080:80"
        build: ./php/
        expose:
            - "9000"
        volumes:
            - ./application/:/var/www/html/application
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
