apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    ports:
        - port: 4406
          targetPort: 3306
    selector:
        app: mysql
    type: NodePort
