apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx  # Unique name for the resource
    labels:
        app: nginx # Grouping the resource
spec:
    replicas: 1
    # A Service uses selector to identify which Pods it routes traffic to.
    selector:
        matchLabels:
            app: nginx
    # The template inside a Deployment defines the Pod specification.
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                -   name: nginx
                    image: 9813276057/application-nginx
                    ports:
                        -   containerPort: 80
                    volumeMounts:
                        -   name: app-volume
                            mountPath: /var/www/html
            volumes:
                -   name: app-volume
                    hostPath:
                        path: /Users/ellite/code/docker/application/application
                        type: Directory
