apiVersion: apps/v1
kind: Deployment
metadata:
    name: php
spec:
    replicas: 1
    selector:
        matchLabels:
            app: php
    template:
        metadata:
            labels:
                app: php
        spec:
            containers:
                -   name: php
                    image: 9813276057/application-php:v0.0.1
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 80
                    volumeMounts:
                        -   mountPath: /var/www/html/application
                            name: application-volume
            volumes:
                -   name: application-volume
                    hostPath:
                        path: /Users/ellite/code/docker/k8/application
                        type: Directory
